### ISSUE TITLE
Proposed changes

### ISSUE THREAD

**Issue by marvinsirait** [arsandev/json-nama-daerah-indonesia#1]
Dear mas Arsan,

Saya ada usulan untuk perbaikan:

1. Penulisan data kabupaten sepertinya harus diperbaiki mengikuti model penulisan pada provinsi DKI Jakarta.

Contoh: {"nama":"Kota Langsa"} sepertinya cukup ditulis "Kota Langsa"

2. Nama provinsi Nanggroe Aceh Darussalam sudah kembali menjadi provinsi Aceh (sejak 2009)

Terima kasih.

**Comment by tegarsantosa** [comment]
Terima kasih masukannya!

fixed.
